config/routes.rb
LoginReg::Application.routes.draw do
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]

  get "/signup",  :to => 'users#new'
  get "/signin",  :to => 'sessions#new'
  get "/signout", :to => 'sessions#destroy'

  root :to => 'users#index'

  

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password

  email_regex = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]+)\z/i

  validates :first_name, :last_name,		:presence 	=> true,
  					:length		            => { :maximum => 50 }
  validates :email_address,		:presence		=> true,
  					:format		            => { :with => email_regex },
           	:uniqueness 	        => { :case_sensitive => false }

  validates :password, 	:presence => true,
  	   			:confirmation 	      => true,
  					:length			          => { :within => 6..40 }

  before_save :encrypt_password

  def has_password?(submitted_password)
  	encrypted_password == encrypt(submitted_password)
  end


  # class method that checks whether the user's email and submitted_password are valid
  def self.authenticate(email, submitted_password)
  	user = find_by_email_address(email)

   	return nil if user.nil?
   	return user if user.has_password?(submitted_password)
  end


  private
  	def encrypt_password
  		# generate a unique salt if it's a new user
  		self.salt = Digest::SHA2.hexdigest("#{Time.now.utc}--#{password}") if self.new_record?
  	
  		# encrypt the password and store that in the encrypted_password field
  		self.encrypted_password = encrypt(password)
  	end

  	# encrypt the password using both the salt and the passed password
  	def encrypt(pass)
  		Digest::SHA2.hexdigest("#{self.salt}--#{pass}")
  	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include SessionsHelper

  def new
  end

  def create
  	user = User.authenticate(params[:session][:email_address], params[:session][:password])

  	if user.nil?
  		flash.now[:error] = "Invalid email/password combination."
  		render :new
  	else
  		sign_in user
  		redirect_to users_path
  		# redirect_to user
  	end

  end

  def destroy
  	sign_out
  	redirect_to signin_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save 
      redirect_to @user, notice: 'User was successfully created.'
    else
      render action: 'new'
    end
  end
  
  def show
    set_user
  end

  def edit
    set_user
  end

  def update
    set_user

    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render action: 'edit'
    end

  end

  def destroy    
    if set_user.destroy
      redirect_to users_path, notice: 'User deleted.'
    else
      render action: 'index'
    end
  end

  private
    
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit([:first_name, :last_name, :email_address, :password])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    session[:user_id] = user.id
    self.current_user = user
  end
  
  # setter method
  def current_user=(user)
    @current_user = user
  end

  # getter method
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_out
    session[:user_id] = nil
    self.current_user = nil
  end

  def current_user?(user)
    user == current_user 
  end

  def deny_access
    redirect_to signin_path, :notice => "Please sign in to access this page."
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
            <!-- <a class="brand" href="/">OMRails</a> -->
            <a class="brand" href="/">Root</a>

            <div class="nav-collapse">
                
                <ul class="nav">
                    <li><a href=""></a></li>
                </ul>

                <ul class="nav pull-right">
                    <% if signed_in? %>
                        <li><a href="/signout">Logout</a></li>
                    <% else %>
                        <li><a href="/signup">Sign Up</a></li>
                        <li><a href="/signin">Login</a></li>
                    <% end %>
                </ul>

            </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LoginReg</title>
  <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rails Bootstrap" %>">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<%= yield %>

</body>
</html>

app/views/users/edit.html.erb
<%= render 'layouts/header' %>

<h1>Update user #<%= @user['id'] %></h1>

<p id="notice"><%= @user.errors.full_messages.first if @user.errors.any? %></p>

<%= simple_form_for @user do |f| %>
	<%= f.input :first_name %>
	<%= f.input :last_name %>
	<%= f.input :email_address %>
	<%= f.input :password %>
	<%= f.button :submit %>
<% end %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<%= render 'layouts/header' %>

<h1>Display all users</h1>

<p id="notice"><%= flash[:notice] %></p>

<table class="table table-striped">
	<tr>
		<th>ID</th>
		<th>First Name</th>
		<th>Last Name</th>
		<th>Email Address</th>
		<th></th>
		<th></th>
		<th></th>
	</tr>
	<% @users.each do |user| %>
		<tr>
			<td><%= user['id'] %></td>		
		    <td><%= user['first_name'] %></td>
		    <td><%= user['last_name'] %></td>
		    <td><%= user['email_address'] %></td>
		    <% if signed_in? %>
			    <td><a href="/users/<%= user['id'] %>/"><button type="button">Show</button></a></td>
			    <td><a href="/users/<%= user['id'] %>/edit"><button type="button">Edit</button></a></td>
			    <td>
			    	<form action="/users/<%= user['id'] %>" method="post">  
						<input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
						<input type='hidden' name="_method" value="delete">
						<input type="submit" value="Delete" />
					</form>
			    </td>
			<% else %>
				<td><a href="/users/<%= user['id'] %>/"><button type="button">Show</button></a></td>
				<td></td>
				<td></td>
			<% end %>
		</tr>
	<% end %>     
</table>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<p id="notice"><%= @user.errors.full_messages.first if @user.errors.any? %></p>

<%= simple_form_for(@user) do |f| %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.input :email_address %>
  <%= f.input :password %>
  <%= f.input :password_confirmation %>
  <%= f.button :submit %>
<% end %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<h1>Display User</h1>

<p id="notice"><%= notice %></p>

<table class="users table">
	<tr>
		<th>ID</th>
		<th>First Name</th>
		<th>Last Name</th>
		<th>Email Address</th>
	</tr>
		<tr>
			<td><%= @user['id'] %></td>		
		    <td><%= @user['first_name'] %></td>
		    <td><%= @user['last_name'] %></td>
		    <td><%= @user['email_address'] %></td>
		</tr>
</table>

<% if signed_in? %>
	<%= link_to 'Edit', edit_user_path(@user) %> |
<% else %>
<% end %>
<%= link_to 'Back', users_path %>